config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get "search_tag" => "post_images#search_tag"
  get "task_calender" => "tasks#task_calender"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follow_list
    end
  end

  resources :post_images,    only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :likes,         only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get :search, on: :collection
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :tasks, only: [:edit, :index, :create, :update, :destroy]
  resources :schedule_days, only: [:create, :show, :destroy]
  resources :day_tasks, only: [:create, :destroy, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :schedule_days, dependent: :destroy

  has_one_attached :task_image
  validates :title_task, :task_place, :content, :status, :task_image, presence: true

  def get_task_image
    unless task_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      task_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    task_image
  end

  enum status: { planning: 0, in_progress: 1, closed: 2 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:create, :task_calender, :index]
  def create
    @task = current_user.tasks.new(task_params)
    unless @task.task_image.present? || !params[:task_image]
      post_image = PostImage.find(params[:task_image])
      @task.task_image.attach(post_image.image.blob)
    end
    if @task.save
      redirect_to tasks_path
    else
      set_task_index
      render :index
    end
  end

  def index
    @task = Task.new
    set_task_index
  end

  def edit
  end

  def update
    if @task.update(task_params)
      set_task_index
      render :index
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    set_task_index
    redirect_to request.referer
  end

  def task_calender
    @tasks = current_user.tasks.all
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def set_task_index
    @task_planning = current_user.tasks.where(status: 0).page(params[:page]).per(4).order(id: :DESC)
    @task_in_progress = current_user.tasks.where(status: 1).page(params[:page]).per(4).order(id: :DESC)
    @task_crosed = current_user.tasks.where(status: 2).page(params[:page]).per(4).order(id: :DESC)
  end

  def task_params
    params.require(:task).permit(:user_id, :title_task, :task_place, :content, :status, :start_time, :end_time, :task_image)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_botton.html.erb
<%= form_with model:task,url:tasks_path,method: :post,local:true do |f|%>
  <%= f.hidden_field :title_task,:value => post_image.title %>
  <%= f.hidden_field :task_place,:value => post_image.place %>
  <%= f.hidden_field :content,:value => post_image.introduction %>
  <%= f.button :type => "提出",class:"btn btn-link m-0 p-0" do %>
    <i class="far fa-address-book fa-2x ml-1 "></i>
  <% end %>
  <%= hidden_field_tag :task_image, post_image.id %>
<% end %>

app/views/tasks/_task_botton_small.html.erb
<%= form_with model:task,url:tasks_path,method: :post,local:true do |f|%>
  <%= f.hidden_field :title_task,:value => post_image.title %>
  <%= f.hidden_field :task_place,:value => post_image.place %>
  <%= f.hidden_field :content,:value => post_image.introduction %>
  <%= f.button :type => "提出",class:"btn btn-link m-0 p-0" do %>
    <i class="far fa-address-book"></i>
  <% end %>
  <%= hidden_field_tag :task_image, post_image.id %>
<% end %>

app/views/tasks/_task_lists.html.erb
<% tasks.each do |task|%>
  <div class="card  mx-auto mb-3 border shadow-lg d-flex justify-content-center w-75  ">
    <div class="row g-0 ">

      <div class="col-md-3 ">
        <%= image_tag task.get_task_image,size: "150x150",class:"rounded-circle m-3 "%>
      </div>
      <div class="col-md-7 ">
        <div class="card-body m-3">
          <h5 class="card-title ">目標 : <%= task.title_task %></h5>
          <p class="card-text">場所 : <%= task.task_place %></p>
          <p class="card-text"><small class="text-muted">やりたい事 : <%= task.content %></small></p>
        </div>
      </div>
      <div class="col-md-2">
        <p class="text-center mt-4">
          <%= link_to edit_task_path(task.id) do %>
            <i class="fas fa-edit fa-2x m-2"></i>
          <% end %>
        </p>
        <p class="text-center mt-4">
          <%= link_to task_path(task.id),method: :delete,data: { confirm: '削除してよろしいですか?' } do%>
            <i class="fas fa-trash-alt fa-2x m-2"></i>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>
   <%= paginate tasks, theme: 'bootstrap-5'%>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row shadow  mb-5 bg-body rounded-3">
    <div class="col ">
      <%=  image_tag @task.task_image, size: "500x500" ,class:"m-3 rounded-circle " %>
    </div>
    <div class="col">
      <div class="p-5">
      <%= form_with model:@task,url:task_path,method: :patch,local:true do |f| %>
      <%= render 'layouts/error_message', model: f.object %>
      <%= f.label :"目標" %><br>
      <%= f.text_field :title_task,autofocus: true, autocomplete: "title_task" ,class:"form-control" %><br>

      <%= f.label :"場所" %><br>
      <%= f.text_field :task_place,autocomplete: "task_place" ,class:"form-control" %><br>

      <%= f.label :"やりたい事" %><br>
      <%= f.text_area :content, rows: '5' ,class:"form-control"%><br>

      <%= f.label :"出発日" %>
      <%= f.date_field :start_time %>

      <%= f.label :"帰着日" %>
      <%= f.date_field :end_time %>

      <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]} %>
      <%= f.submit "変更" %>

      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container m-auto ">
  <%= render 'layouts/error_message', model: @task %>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">計画中</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">進行中</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">達成済</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="new_task-tab" data-toggle="tab" href="#new_task" role="tab" aria-controls="new_task" aria-selected="false">新規投稿</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="">
    　　<%= render 'tasks/task_lists',tasks: @task_planning %>
  　　</div>
  　</div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="">
    　　<%= render 'tasks/task_lists',tasks: @task_in_progress %>
  　　</div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <div class="">
    　　<%= render 'tasks/task_lists',tasks: @task_crosed %>
  　　</div>
    </div>
    <div class="tab-pane fade" id="new_task" role="tabpanel" aria-labelledby="new_task-tab">
      <div class="d-flex justify-content-center mx-auto mt-2">

        　<%= form_with model:@task,url:tasks_path,method: :post,local:true do |f|%>

        　<%= f.label :"目標" %><br>
          <%= f.text_field :title_task,autofocus: true, autocomplete: "title_task" ,class:"form-control" %><br>

          <%= f.label :"場所" %><br>
          <%= f.text_field :task_place,autocomplete: "task_place" ,class:"form-control" %><br>

          <%= f.label :"やりたい事" %><br>
          <%= f.text_area :content, rows: '3' ,class:"form-control"%><br>

          <%= f.label :"出発日" %>
          <%= f.date_field :start_time %>

          <%= f.label :"帰着日" %>
          <%= f.date_field :end_time %>

          <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]},class:"m-3" %><br/>

　　　　　<%= f.label :"画像" %>
          <%= f.file_field :task_image,accept: "image/*" %><br/>
          <div class="d-flex justify-content-center">
            <%= f.submit "投稿" ,class:"btn btn-primary rounded-pill m-3 "%>
          </div>

    　　<% end %>
  　　</div>
    </div>
  </div>
</div>

app/views/tasks/task_calender.html.erb
<div class="container w-75">
  <%= month_calendar events: @tasks  do |date, tasks| %>
    <%= date.day %>

    <% tasks.each do |task| %>
      <div>
        <%= link_to schedule_days_path({schedule_day:{schedule_day: date,task_id: task.id}}), method: :post do %>
      
          <p class=" p-0 m-0 text-c"><%= task.title_task %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>