config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get "search_tag" => "post_images#search_tag"
  get "task_calender" => "tasks#task_calender"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follow_list
    end
  end

  resources :post_images,    only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :likes,         only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get :search, on: :collection
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :tasks, only: [:edit, :index, :create, :update, :destroy]
  resources :schedule_days, only: [:create, :show, :destroy]
  resources :day_tasks, only: [:create, :destroy, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :nickname, presence: true

  has_one_attached :profile_image
  has_many :post_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :schedule_days, dependent: :destroy
  has_many :day_tasks, dependent: :destroy

  has_many :active_notifications,  class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.nickname = "ゲストユーザー"
    end
  end

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end
  # フォローしている
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされてる
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしている人
  has_many :follower_user, through: :followed, source: :follower
  # フォローされている人
  has_many :following_user, through: :follower, source: :followed

  # 1. followメソッド　＝　フォローする
  def follow(user_id)
    follower.create!(followed_id: user_id)
  end

  # 2. unfollowメソッド　＝　フォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # 3. followingメソッド　＝　既にフォローしているかの確認
  def following?(user)
    following_user.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    return if temp.present?

    notification = current_user.active_notifications.new(
      visited_id: id,
      action: 'follow'
    )
    notification.save if notification.valid?
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  before_action :set_user

  def show
  end

  def edit
    redirect_to post_images_path unless current_user.id == @user.id
  end

  def update
    @user.update(user_params)

    render :show
  end

  def follow_list
    @users_follower = @user.follower_user
    @users_followed = @user.following_user
    redirect_to post_images_path unless current_user.id == @user.id
  end

  private

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_followed.html.erb
<% if users_followed.exists? %>
    <p class="text-center"><span id="btn-b<%= current_user.id %>"><%= users_followed.count %></span>人フォロー中</p>
  <% users_followed.each do |followed| %>
    <div class="card p-0 mx-auto border shadow-lg d-flex justify-content-center ">
      <div class="row g-0 p-0 ">
        <div class="col-md-2 ps-5 d-flex align-items-center">
         <%= render 'users/user_link',user: followed %>
        </div>
        <div class="col-md-4 d-flex align-items-center"><P class="text-center m-0 p-0"><%= followed.nickname %>さん</P></div>

        <div class="col-md-3 d-flex align-items-center">
          <div class="card-body p-0">
            <p class="card-text m-0 p-0"><small>フォロー:</small><span id="btn-a<%= followed.id %>"><%= followed.following_user.count %></span></p>
            <p class="card-text m-0 p-0"><small>フォロワー:</small><span id="btn-b<%= followed.id %>"><%= followed.follower_user.count %></span></p>
          </div>
        </div>
        <div class="col-md-3">
          <div class=" my-4 mx-0 p-0">
            <div id="follow_button<%= followed.id %>">
            <%= render 'relationships/follow_button',user: followed %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_follower.html.erb
<% if users_follower.exists? %>
     <p class="text-center"><span id="btn-a<%= current_user.id %>"><%= users_follower.count %></span>人フォロワー</p>
    <% users_follower.each do |follower| %>
      <div class="card p-0 mx-auto border shadow-lg d-flex justify-content-center ">
        <div class="row g-0 ">
          <div class="col-md-2 ps-5 d-flex align-items-center">
            <%= render 'users/user_link',user: follower %>
          </div>
          <div class="col-md-4 my-4"><P class="text-center m-0 p-0"><%= follower.nickname %>さん</P></div>

          <div class="col-md-3 d-flex align-items-center">
            <div class="card-body p-0">
              <p class="card-text m-0 p-0"><small>フォロー:</small><span id="btn-a<%= follower.id %>"><%= follower.following_user.count %></span></p>
              <p class="card-text m-0 p-0"><small>フォロワー:</small><span id="btn-b<%= follower.id %>"><%= follower.follower_user.count %></span></p>
            </div>
          </div>
          <div class="col-md-3">
            <div class=" my-4 mx-0 p-0">
              <div id="follow_button<%= follower.id %>">
               <%= render 'relationships/follow_button',user: follower%>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>ユーザーはいません</p>
<% end %>

app/views/users/_user_link.html.erb
<%= link_to  user_path(user.id) do %>
  <%= image_tag user.get_profile_image,size:'50x50',class:"rounded-circle border border-dark" %>
<% end %>

app/views/users/edit.html.erb
<div class="container ">
  <div class="row">
    <div class="col d-flex justify-content-center">


<%= form_with model: @user,url: user_path(@user.id),method: :patch, local: true do |f| %>

  <div><h2>公開プロフィール</h2></div>

  <div class="field m-3">
    <%= f.label :ニックネーム %>
    <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname",placeholder: "ニックネーム",class:"form-control" %>
  </div>


  <div class="field m-3">
    <%= f.label :名前 %>
    <%= f.text_field :name, autocomplete: "name",placeholder: "名前",class:"form-control" %>
  </div>


  <div class="field m-3">
    <%= f.label :メールアドレス%>
    <%= f.email_field :email, autocomplete: "email",placeholder: "メールアドレス",class:"form-control" %>
  </div>


  <div class="field m-3">
    <%= f.file_field :profile_image,accept: "image/*" %>
  </div>

  <div class="actions d-flex justify-content-center">
    <%= f.submit "変更" ,class:"btn btn-primary rounded-pill"%>
  </div>


 <% end %>



    </div>
  </div>
</div>

app/views/users/follow_list.html.erb
<div class="container w-50">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">フォロー中</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">フォロワー</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <div id="followed"><%= render 'users/followed',users_followed: @users_followed %></div>
      </div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab"><%= render 'users/follower',users_follower: @users_follower %></div>
    </div>
</div>

app/views/users/notifications.html.erb
<div class="container w-50">
     <h3 class="text-center">通知</h3>
  <div class="row">

    <%= link_to destroy_all_notifications_path, method: :delete do %>
        <i class="fas fa-trash" style="color: black;"></i>
        <h7 style="color: black;">全削除</h7>
    <% end %>

    <div class="col d-flex justify-content-center w-50">
      <% @notifications = @notifications.where.not(visiter_id: current_user.id) %>
        <% if @notifications.exists? %>
          <% @notifications.each do |notification| %>
            <% visiter = notification.visiter %>
            <% visited = notification.visited %>
          <div>
          <span class="border-bottom border-dark">
            <%=link_to user_path(visiter) do %>
              <%= visiter.nickname %> さんが
            <% end %>

          <% case notification.action %>
            <% when 'follow' then %>
              あなたをフォローしました

            <% when 'like' then %>
              <%= link_to 'あなたの投稿', notification.post_image, style: "font-weight: bold;"%> にいいねしました

            <% when 'comment' then %>
              <% if notification.post_image.user_id == visited.id %>
                <%= link_to "あなたの投稿", notification.post_image, style: "font-weight: bold;"%>
              <% else %>
                <strong>
                  <%= link_to notification.post_image do %>
                    <%=notification.post_image.user.nickname  %>の投稿
                  <% end %>
                </strong>
              <% end %>
                     にコメントしました
               <p><%= PostComment.find_by(id: notification.post_comment_id)&.comment %></p>

        <% end %>
          <%= time_ago_in_words(notification.created_at).downcase %>
      <% end %>
    </span>
   <% else %>
    <p class="text-center">通知はありません</p>

  </div>
   <% end %>
<%= paginate @notifications, theme: 'bootstrap-5' %>




    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-6 d-flex justify-content-end">
    <div class="card" style="width: 75%; height: 445px;">
     <div class="d-flex justify-content-center mt-4"><%= image_tag @user.get_profile_image,size:"100x100",class:"border border-dark rounded-circle mt-3" %></div>
     <div class="card-body">
      <% if @user.id == current_user.id %>
             <h4 class="text-center">
              　Photos:<%= @user.post_images.count %>  |  Tasks:<%= @user.tasks.count %></h4>
             <p class="text-center">ニックネーム:<strong><%= @user.nickname %></strong></p>
             <p class="text-center">名前:<strong><%= @user.name %></strong></p>
             <p class="text-center">e-mail:<%= @user.email %></p>
             <%= link_to follow_list_user_path do %>
                  <p class="text-center">
                   フォロワー:<span id="btn-b<%= @user.id %>"><%= @user.follower_user.count %></span>  |  フォロー中:<span id="btn-a<%= @user.id %>"><%= @user.following_user.count %></span>
                  </p>
       <% end %>
               <div class="d-flex justify-content-center">
                   <% if @user.name != "guestuser" %>
                    <%= link_to 'プロフィール編集',edit_user_path(@user.id),class:"btn btn-success mr-1" %>
                   <% end %>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete,data: { confirm: 'ログアウトしてよろしいですか?' },class:"btn btn-danger" %>
              </div>
      <% else %>
             <p class="text-center"><strong><%= @user.nickname %></strong></p>
             <p class="text-center">photos:<%= @user.post_images.count %></p>
             <p class="text-center">
             フォロワー:<span id="btn-b<%= @user.id %>"><%= @user.follower_user.count %></span>  |  フォロー中:<span id="btn-a<%= @user.id %>"><%= @user.following_user.count %></span>
             </p>
             <div class="d-flex justify-content-center" id="follow_button<%= @user.id %>">
               <div><%= render 'relationships/follow_button',user: @user%></div>
             </div>
      <% end %>
    </div>
   </div>
  </div>
  <div class="col-6 d-flex justify-content-start">
   <div class="card m-0 p-0 border-0" style="width: 426px; height: 402px;">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
     <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><i class="fas fa-th fa-lg"></i></a>
     </li>
     <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fas fa-heart fa-lg"></i></a>
     </li>
    </ul>
    <div class="list p-0">
     <div class="tab-content" id="myTabContent">
       <div class="tab-pane fade show active box2" style="width: 430px; height: 402px;" id="home" role="tabpanel" aria-labelledby="home-tab">
        <% @user.post_images.each do |posts| %>
         <%= link_to post_image_path(posts.id) do %>
          <%= image_tag posts.get_image,size:"134x134" %>
         <% end %>
        <% end %>
       </div>
       <div class="tab-pane fade box2 " style="width: 430px; height: 402px;" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <% @likes = @user.likes.order(created_at: :desc) %>
        <% @likes.each do |likes| %>
         <%= link_to post_image_path(likes.post_image.id) do %>
          <%= image_tag likes.post_image.get_image,size:"134x134" %>
         <% end %>
        <% end %>
       </div>
     </div>
    </div>
    </div>
   </div>
 </div>
</div>

app/views/users/task_list.html.erb
<div class="container m-auto ">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">計画中</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">進行中</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">達成済</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="new_task-tab" data-toggle="tab" href="#new_task" role="tab" aria-controls="new_task" aria-selected="false">新規投稿</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="">
    　　<%= render 'tasks/task_lists',tasks: @task_planning %>
  　　</div>
  　</div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="">
    　　<%= render 'tasks/task_lists',tasks: @task_in_progress %>
  　　</div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <div class="">
    　　<%= render 'tasks/task_lists',tasks: @task_crosed %>
  　　</div>
    </div>
    <div class="tab-pane fade" id="new_task" role="tabpanel" aria-labelledby="new_task-tab">
      <div class="">

        　<%= form_with model:@task,url:tasks_path,method: :post,local:true do |f|%>
          <%= render 'layouts/error_message', model: f.object %>
        　<%= f.label :"目標" %><br>
          <%= f.text_field :title_task,autofocus: true, autocomplete: "title_task" ,class:"form-control" %><br>

          <%= f.label :"場所" %><br>
          <%= f.text_field :task_place,autocomplete: "task_place" ,class:"form-control" %><br>

          <%= f.label :"やりたい事" %><br>
          <%= f.text_area :content, rows: '5' ,class:"form-control"%><br>

          <%= f.label :start_time %>
          <%= f.date_field :start_time %>

          <%= f.label :end_time %>
          <%= f.date_field :end_time %>

          <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]} %>

　　　　　<%= f.label :"画像" %>
          <%= f.file_field :task_image,accept: "image/*" %><br/>

          <%= f.submit "投稿" %>

    　　<% end %>
  　　</div>
    </div>
  </div>
</div>