config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get "search_tag" => "post_images#search_tag"
  get "task_calender" => "tasks#task_calender"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follow_list
    end
  end

  resources :post_images,    only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :likes,         only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get :search, on: :collection
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :tasks, only: [:edit, :index, :create, :update, :destroy]
  resources :schedule_days, only: [:create, :show, :destroy]
  resources :day_tasks, only: [:create, :destroy, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  has_one_attached :image
  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :post_comments, dependent: :destroy
  has_many   :notifications, dependent: :destroy
  has_many :post_image_tags, dependent: :destroy
  has_many :tags, through: :post_image_tags

  validates :title, length: { maximum: 50 }
  validates :title, :place, :introduction, :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def self.searching(keyword)
    where(['title LIKE ? or place LIKE ? or introduction LIKE ?', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visiter_id = ? and visited_id = ? and post_image_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_image_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      notification.checked = true if notification.visiter_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    # 取得したユーザーIDの分だけ通知を作成するとき、同じ通知が複数回登録されてしまうことを防ぐため = distinctメソッド
    temp_ids = PostComment.select(:user_id).where(post_image_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_image_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end

  def save_tags(tags)
    post_image_tags.destroy_all
    tags.each do |tag|
      tag = Tag.find_or_create_by(name: tag)
      post_image_tags.find_or_create_by(tag_id: tag.id)
    end
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :set_post_image, except: [:new, :create, :index, :search, :search_tag]
  before_action :set_task, except: [:new, :create, :edit]

  def new
    @user = current_user
    @post_image = PostImage.new
  end

  def create
    @post_image = current_user.post_images.new(image_params)
    unless @post_image.star.presence
      @post_image.star = 0
    end
    if @post_image.save
      flash.now[:notice] = '投稿しました'
      tags = Vision.get_image_data(@post_image.image)
      @post_image.save_tags(tags)

      redirect_to post_images_path
    else
      flash.now[:alert] = '投稿できませんでした'
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page]).per(12)
  end

  def show
    @post_comment = PostComment.new
  end

  def destroy
    @post_image.destroy
    @post_images = PostImage.page(params[:page]).per(12)
    render :index
  end

  def edit
    redirect_to post_images_path unless current_user.id == @post_image.user_id
  end

  def update
    @post_image.update(image_params)
    tags = Vision.get_image_data(@post_image.image)
    @post_image.save_tags(tags)
    @post_comment = PostComment.new
    render :show
  end

  def search
    if params[:keyword].present?
      @post_images = PostImage.searching(params[:keyword]).page(params[:page]).per(12)
    else
      @post_images = PostImage.page(params[:page]).per(12)
      flash.now[:alert] = '未入力です。'
      render :index
    end
  end

  def search_tag
    @tag_list = Tag.all
    if params[:tag_id].blank?
      render :search_tag
    else
      @tag = Tag.find(params[:tag_id])
      @post_images = @tag.post_images.page(params[:page]).per(12)
    end
  end

  private

  def set_post_image
    @post_image = PostImage.find(params[:id])
  end

  def set_task
    @task = Task.new
  end

  def image_params
    params.require(:post_image).permit(:title, :place, :introduction, :user_id, :image, :star)
  end
end

app/views/post_images/_post_image_list.html.erb
<% post_images.each do |post_image|%>
  <div class="card1 card shadow-lg shadow mb-3">
    <%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image, class:"thumb-300 card-img-top"; %>
    <% end %>

    <div class="card-body py-0 m-0">
      <div class="row">
        <div class="col-lg-1 mb-0 ">
          <div id = "likes_button_small<%= post_image.id %>">
            <%= render 'likes/likes_button_small',post_image: post_image %>
          </div>
        </div>

        <div class="col-lg-1 d-flex align-items-center">
          <%= link_to post_image_path(post_image.id) do %>
            <i class="far fa-comment"></i>
          <% end %>
        </div>

        <div class="col-lg-6 d-flex align-items-start justify-content-center ml-4">
          <%=render 'post_image_star',post_image: post_image%>
        </div>

        <div class="col-lg-1  d-flex align-items-start ">
          <%= link_to user_path(post_image.user.id) do %>
            <i class="fas fa-user"></i>
          <% end %>
        </div>

        <div class="col-lg-1 d-flex align-items-start ">
          <%= render 'tasks/task_botton_small',task: task ,post_image: post_image %>
        </div>
      </div>

      <div class="">
        <small>
          <p class="fs-6 fw-lighter  p-0 m-0 text-break text-c text-lowercase">
            <%= post_image.title %>
          </p>
        </small>
        <small>
          <p class="fs-6 p-0 m-0 text-lowercase">
              <i class="fas fa-tag"></i>
              <% post_image.tags.each do |tag| %>
                <%=link_to tag.name,search_tag_path(tag_id: tag.id) %>
              <% end %>
          </p>
        </small>
      </div>
    </div>
  </div>
<% end %>

app/views/post_images/_post_image_star.html.erb
<!--<p>評価 :<%#= post_image.star%>点</p>-->
  <div id="star-rate<%= post_image.id%>"></div>
<script>
    $('#star-rate<%= post_image.id %>').empty();
    $('#star-rate<%= post_image.id%>').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: <%= post_image.star %>,
    });
</script>

app/views/post_images/edit.html.erb
<div class="container">
  <div class="row shadow  mb-5 bg-body rounded-3">
    <div class="col ">
      <%= image_tag @post_image.get_image, size: "500x500" ,class:"m-3 rounded-circle " %>
    </div>
    <div class="col">
      <div class="p-5">
        <%= form_with model:@post_image,url:post_image_path,method: :patch, local:true do |f| %>
                <%= f.label :"タイトル" %><br/>
                <%= f.text_field :title ,autofocus: true ,autocomplete: "title" ,class:"form-control"%><br/>

                <%= f.label :"場所" %><br/>
                <%= f.text_field :place , autocomplete: "place",class:"form-control" %><br/>

                <%= f.label :"説明" %><br/>
                <%= f.text_area :introduction , autocomplete: "introduction" ,class:"form-control"%><br/>

                <%= f.label :image %><br/>
                <%= f.file_field :image,accept: "image/*" %><br/>

                <%= f.submit '編集' %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/index.html.erb
<div class="container">
  <div class="list">
    <%= render 'post_images/post_image_list',post_images: @post_images,task: @task %>
  </div>
  <div class="d-flex justify-content-center"><%= paginate @post_images, theme: 'bootstrap-5'%></div>
</div>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row">

    <div class="col d-flex justify-content-center">

              <%= form_with model:@post_image,url:post_images_path,method: :post, local:true do |f| %>
               <%= render 'layouts/error_message', model: f.object %>
              <div class="field ">
                <%= f.label :"タイトル" %><br/>
                <%= f.text_field :title ,autofocus: true ,autocomplete: "title",class:"form-control" %><br/>
              </div>

              <div class="field">
                <%= f.label :"場所" %><br/>
                <%= f.text_field :place , autocomplete: "place",class:"form-control" %><br/>
              </div>

              <div class="field ">
                <%= f.label :"説明" %><br/>
                <%= f.text_area :introduction , autocomplete: "introduction",class:"form-control" %><br/>
              </div>


              <div class="form-group row " id="star">
                <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
                <%= f.hidden_field :star, id: :review_star %>
              </div>

                          <!-- 評価javascript -->
              <script>
              $('#star').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',

                scoreName: 'post_image[star]',
                half: false,
              });
              </script>

              <div class="field ">
                <%= f.label :"画像" %>
                <%= f.file_field :image,accept: "image/*" %><br/>
              </div>

                <div class="d-flex justify-content-center">
                  <%= f.submit '投稿',class:"btn btn-primary rounded-pill m-3 " %>
                </div>


              <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/post_images/search.html.erb
<div class="container">
  <% if @post_images.count == 0 %>
    検索にマッチするものはありませんでした
  <% else %>
    <%= @post_images.count %>件ヒットしました
  <% end %>
   
  <div class="list">
    <%= render 'post_image_list',post_images: @post_images,task: @task%>
  </div>
  <div class="d-flex justify-content-center"><%= paginate @post_images, theme: 'bootstrap-5'%></div>
</div>

app/views/post_images/search_tag.html.erb
<div class="container">
  <p>
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      <span><i class="fas fa-tag"></i>タグ一覧</span>
    </a>
  </p>
<div class="collapse" id="collapseExample">
  <div class=" card-body ">
   <% @tag_list.each do |tag| %>
      <span><%=link_to tag.name,search_tag_path(tag_id: tag.id),class:"text-lowercase" %></span>
    <% end %>
  </div>
</div>

  <% unless @post_images.blank? %>
    <div class="list">
      <%= render 'post_images/post_image_list',post_images: @post_images,task: @task %>
    </div>
  <% else %>
  <p class="text-center">タグ一覧からタグを選択して下さい。</p>
  <% end %>

</div>

app/views/post_images/show.html.erb
<div class="container ">
  <div class="row shadow  mb-5 bg-body rounded-3">
    <div class="col ">
      <%= image_tag @post_image.get_image, size: "500x500" ,class:"m-3 rounded-circle " %>
    </div>
    <div class="col pt-3">

      <div class="position">
        <div class="point d-flex align-items-center">
          <% if @post_image.user == current_user %>
              <div id="likes_button<%= @post_image.id %>">
                <%= render 'likes/likes_button',post_image: @post_image%>
              </div>

              <%= link_to edit_post_image_path(@post_image.id) do %>
              <i class="fas fa-edit fa-2x m-2"></i>
              <% end %>
              <%= link_to post_image_path(@post_image.id), method: :delete ,data: { confirm: '削除してよろしいですか?' }  do %>
              <i class="fas fa-trash-alt fa-2x m-2"></i>
              <% end %>

          <% else %>
              <div id="likes_button<%= @post_image.id %>">
                <%= render 'likes/likes_button',post_image: @post_image%>
              </div>

               <div id="follow_button<%= @post_image.user.id %>">
                 <%= render 'relationships/follow_button',user: @post_image.user%>
               </div>

              <%= render 'tasks/task_botton',task: @task ,post_image: @post_image %>
          <% end %>
        </div>

      </div>


        <div class="row mt-4 mb-1">
          <div class="col-1 p-0 d-flex align-items-center">
            <%= render 'users/user_link',user: @post_image.user %>
          </div>
          <div class="col-11 p-2 ">
            <p class="m-0 p-0 text-left"><%= @post_image.user.nickname %>さん</p>
            <p class="m-0 p-0 text-left">フォロワー：<span id="btn-b<%= @post_image.user.id %>"><%= @post_image.user.follower_user.count %></span></p>
          </div>
        </div>

          <div class="row ">
            <div class="col">
              <div class=""><h5 class="text-break"><%= @post_image.title %></h5></div>
              <div class="d-inline-flex mr-2 d-flex align-items-center">
                <%=render 'post_images/post_image_star',post_image: @post_image %>
              </div>
              <div class="d-inline-flex d-flex align-items-center">
                <i class="fas fa-tag "></i>
                <% @post_image.tags.each do |tag| %>
                  <%=link_to tag.name,search_tag_path(tag_id: tag.id),class:"text-lowercase m-1" %>
                <% end %>
              </div>


               <div class="m-2"><P class="text-break"><%= @post_image.place %></P></div>
              <div class="m-2"><P class="text-break"><small class="text-muted"><%= @post_image.introduction %></small></P></div>
            </div>
            </div>

         <div class="row">
           <div class="col">
              <div class="box m-2">
                <div id="comments_index">
                  <%= render 'post_comments/post_comments',post_image: @post_image %>
                </div>
              </div>
              <p class="m-2">風景について質問をしたり、感想を伝えましょう！</p>
                <div class="">
                  <%= render 'post_comments/post_comments_form',post_image: @post_image,post_comment: @post_comment %>
                </div>
          </div>
    </div>
  </div>
</div>