config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  get "search_tag" => "post_images#search_tag"
  get "task_calender" => "tasks#task_calender"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follow_list
    end
  end

  resources :post_images,    only: [:new, :index, :show, :edit, :create, :destroy, :update] do
    resource :likes,         only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get :search, on: :collection
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :tasks, only: [:edit, :index, :create, :update, :destroy]
  resources :schedule_days, only: [:create, :show, :destroy]
  resources :day_tasks, only: [:create, :destroy, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <title>LandscapeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <body>
    <header class="shadow-sm mb-3">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag 'logo.png',size:"60x60"%></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>

        <li class="nav-item  mx-3 d-flex align-items-center">
          <%= link_to 'Home', post_images_path,class:'p-3 mb-2 rounded-pill btn btn-outline-danger' %>
        </li>

        <li class="nav-item  mx-3 d-flex align-items-center">
           <%= link_to '新規投稿', new_post_image_path,class:"p-3 mb-2 rounded-pill btn btn-outline-danger"%>
        </li>

        <li class="nav-item mx-3 d-flex align-items-center">
          <%= link_to "タグ検索",search_tag_path,class:"p-3 mb-2 rounded-pill btn btn-outline-danger"%>
        </li>

         <%= form_with url: search_post_images_path,class: "d-flex m-3", method: :get, local: true do |f| %>
                  <%= f.text_field :keyword ,class:"form-control ",type:"search"%>
                  <%= f.submit :search,class:"btn btn-outline-success",type:"submit" %>
                  <% end %>
        <li class="nav-item  d-flex align-items-center">
          <%= link_to task_calender_path do %>
            <i class="fas fa-calendar-check fa-2x"></i>
          <% end %>
        </li>

        <li class="nav-item ml-2 d-flex align-items-center">
          <%= link_to tasks_path do %>
           <i class="far fa-address-book fa-2x "></i>
          <% end %>
        </li>

        <li class="nav-item ml-2 d-flex align-items-center">
          <%= render 'notifications/notification_check_button'%>
        </li>

        <li class="nav-item ml-2 d-flex align-items-center">
          <%= render 'users/user_link',user: current_user %>
        </li>
        <% else %>

        <li class="nav-item m-3">
          <%= link_to "無料登録",new_user_registration_path, class:"p-3 mb-2 bg-light text-dark rounded-pill"%>
        </li>
        <li class="nav-item m-3">
           <%= link_to "ログイン",new_user_session_path,class:"p-3 mb-2 bg-danger text-white rounded-pill" %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
   <main class="mb-5">
     <div id="flash-message">
       <%= render 'layouts/flash' %>
     </div>
     <%= yield %>
   </main>
   <footer class="fixed-bottom">
     <div class="p-1 bg-danger ">
        <p class="text-center"><i class="fab fa-twitter"></i><i class="fab fa-github"></i><i class="fab fa-instagram"></i></p>
     </div>
   </footer>
  </body>
</html>